# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    # We'll use the single-file case for these runs
    NF_WORKFLOW_OPTS: "--fastq test_data/case01"
    CI_FLAVOUR: "new" # set to "classic" for old-style CI
    TEST_CMD: "bash test/run_fastq_ingress_test.sh"




# Remove this block in downstream templates
singularity-run:
    tags: [] # no need for big ram
# end

aws-run:
    artifacts:
        when: always
        paths:
            - ${CI_PROJECT_NAME}
            - .nextflow.log
        exclude: [] # give me everything pal
    allow_failure: true


docker-run:

    # Remove this directive in downstream templates
    tags: [] # no need for big ram

    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            # TODO: do we really need to run all from s3?
            - MATRIX_NAME: [
                "single-file", "emu", "combine-counts-genus"
                ]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #   being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "single-file"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/case01/S1/Zymo_ONT.fastq.gz"
        - if: $MATRIX_NAME == "emu"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/case01/"
        - if: $MATRIX_NAME == "combine-counts-genus"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/case01/ --rank genus --split_tables --counts"
