name: emu-nf-workflow
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - biopython
    - python >=3.6,<=3.8.12
    - pysam >=0.15
    - numpy >=1.11
    - pandas >=1.1
    - flatten-dict
    - minimap2 >=2.22
    - aplanat >=0.5.0
    - fastcat
    - epi2melabs
    - emu >=3.0
    - osfclient